Aim for more reuse

diff --git a/2-compiler/Dockerfile b/2-compiler/Dockerfile
--- a/2-compiler/Dockerfile
+++ b/2-compiler/Dockerfile
@@ -1,28 +1,45 @@
 ARG BASE_IMAGE
 
-FROM ${BASE_IMAGE}
+FROM ${BASE_IMAGE} AS builder
 
 ARG COMPILER
 ARG SPACK_INSTALL_ARGS
 
-ENV SPACK_INSTALL_ARGS=${SPACK_INSTALL_ARGS:-"--verbose --test=all --fail-fast"}
+# No --test=all because many tests fail
+ENV SPACK_INSTALL_ARGS=${SPACK_INSTALL_ARGS:-"--show-log-on-error --fail-fast"}
 ENV COMPILER=${COMPILER}
 
-RUN set -ex \
- && ( [ "gcc@7.5.0" = "${COMPILER}" ] || spack config remove packages:gcc ) \
- && COMPSPEC=${COMPILER/clang/llvm} \
+RUN COMPSPEC=${COMPILER/clang/llvm} \
  && COMPSPEC="${COMPSPEC} $([[ ${COMPILER} =~ "^gcc" ]] && echo -n "~bootstrap" || true)" \
+ && echo COMPSPEC="${COMPSPEC}" >> env.sh
+
+RUN ( [ "gcc@7.5.0" = "${COMPILER}" ] || spack config remove packages:gcc )
+
+RUN . env.sh \
  && spack solve -I                      --reuse ${COMPSPEC} target=x86_64 \
- && spack install ${SPACK_INSTALL_ARGS} --reuse ${COMPSPEC} target=x86_64 \
+ && spack install ${SPACK_INSTALL_ARGS} --reuse ${COMPSPEC} target=x86_64
+
+RUN . env.sh \
  && spack load ${COMPSPEC} \
- && spack compiler find \
- && spack unload ${COMPSPEC} \
- && spack config add "packages:all:compiler:[${COMPILER}]" \
- && sed 's/target:.*/target: x86_64/' -i /root/.spack/linux/compilers.yaml \
- && DEFAULT_F77="$(grep '\bf77\b' ~/.spack/linux/compilers.yaml | grep -v '\bnull\b' | head -n 1 | sed 's/.*:\s*//')" \
- && sed -i "s#f77\s*:\s*null#f77: ${DEFAULT_F77}#I" ~/.spack/linux/compilers.yaml \
- && DEFAULT_FC="$(grep '\bfc\b' ~/.spack/linux/compilers.yaml | grep -v '\bnull\b' | head -n 1 | sed 's/.*:\s*//')" \
- && sed -i "s#fc\s*:\s*null#fc: ${DEFAULT_FC}#I" ~/.spack/linux/compilers.yaml \
- && find -L ${SPACK_ROOT}/opt/spack -type f -exec readlink -f '{}' \; \
+ && spack compiler find
+RUN spack config add "packages:all:compiler:[${COMPILER}]"
+RUN sed 's/target:.*/target: x86_64/' -i ${SPACK_HOME}/linux/compilers.yaml
+RUN DEFAULT_F77="$(grep '\bf77\b' ~/.spack/linux/compilers.yaml | grep -v '\bnull\b' | head -n 1 | sed 's/.*:\s*//')" \
+ && sed -i "s#f77\s*:\s*null#f77: ${DEFAULT_F77}#I" ~/.spack/linux/compilers.yaml
+RUN DEFAULT_FC="$(grep '\bfc\b' ~/.spack/linux/compilers.yaml | grep -v '\bnull\b' | head -n 1 | sed 's/.*:\s*//')" \
+ && sed -i "s#fc\s*:\s*null#fc: ${DEFAULT_FC}#I" ~/.spack/linux/compilers.yaml
+
+RUN find -L ${SPACK_ROOT}/opt/spack -type f -exec readlink -f '{}' \; \
   | xargs file -i | awk -F: '/(x-executable|x-archive|x-sharedlib); charset=binary/ {print $1}' \
-  | xargs -r strip -s || true
+  | xargs -r strip -s || echo "Failed strip"
+
+RUN spack clean -a
+
+
+FROM ${BASE_IMAGE}
+
+ARG COMPILER
+ENV COMPILER=${COMPILER}
+
+COPY --from=builder ${SPACK_HOME} ${SPACK_HOME}
+COPY --from=builder ${SPACK_ROOT} ${SPACK_ROOT}
diff --git a/3-baselibs/Dockerfile b/3-baselibs/Dockerfile
--- a/3-baselibs/Dockerfile
+++ b/3-baselibs/Dockerfile
@@ -1,27 +1,35 @@
 ARG BASE_IMAGE
 
-FROM ${BASE_IMAGE}
+FROM ${BASE_IMAGE} AS builder
 
-ARG CMAKE_VERSION
 ARG SPACK_INSTALL_ARGS
 
-ENV SPACK_INSTALL_ARGS=${SPACK_INSTALL_ARGS:-"--verbose --test=all --fail-fast"}
-ENV CMAKE=cmake${CMAKE_VERSION}
+ENV SPACK_INSTALL_ARGS=${SPACK_INSTALL_ARGS:-"--show-log-on-error --test=all --fail-fast"}
 
-RUN set -ex \
- && spack solve -I                      --reuse "cmake"    "~ncurses" "~ownlibs" target=x86_64 "%${COMPILER}" \
- && spack install ${SPACK_INSTALL_ARGS} --reuse "cmake"    "~ncurses" "~ownlibs" target=x86_64 "%${COMPILER}" \
- && spack solve -I                      --reuse "${CMAKE}" "~ncurses" "~ownlibs" target=x86_64 "%${COMPILER}" \
- && spack install ${SPACK_INSTALL_ARGS} --reuse "${CMAKE}" "~ncurses" "~ownlibs" target=x86_64 "%${COMPILER}"
+RUN spack solve -I                      --reuse "cmake~ncurses~ownlibs target=x86_64 ^curl tls=openssl" \
+ && spack install ${SPACK_INSTALL_ARGS} --reuse "cmake~ncurses~ownlibs target=x86_64 ^curl tls=openssl"
 
-RUN mkdir /opt/baselibs-env
-COPY baselibs.yaml /opt/baselibs-env/spack.yaml
-RUN sed -i "s/@COMPILER@/${COMPILER}/" /opt/baselibs-env/spack.yaml \
- && spack env activate /opt/baselibs-env \
+RUN spack solve -I                      --reuse "cmake@3.10.0~ncurses~ownlibs target=x86_64 ^curl tls=openssl" \
+ && spack install ${SPACK_INSTALL_ARGS} --reuse "cmake@3.10.0~ncurses~ownlibs target=x86_64 ^curl tls=openssl"
+
+RUN mkdir -p ${SPACK_ROOT}/var/environments/baselibs
+COPY baselibs.yaml ${SPACK_ROOT}/var/environments/baselibs/spack.yaml
+RUN sed -i "s/@COMPILER@/${COMPILER}/" ${SPACK_ROOT}/var/environments/baselibs/spack.yaml
+
+RUN spack env activate ${SPACK_ROOT}/var/environments/baselibs \
  && spack config add "packages:all:target:[x86_64]" \
  && spack config add "packages:all:compiler:[${COMPILER}]" \
  && spack concretize --test=all --reuse \
- && spack install ${SPACK_INSTALL_ARGS} \
- && find -L ${SPACK_ROOT}/opt/spack -type f -exec readlink -f '{}' \; \
+ && spack install ${SPACK_INSTALL_ARGS}
+
+RUN spack clean -a
+
+RUN find -L ${SPACK_ROOT}/opt/spack -type f -exec readlink -f '{}' \; \
   | xargs file -i | awk -F: '/(x-executable|x-archive|x-sharedlib); charset=binary/ {print $1}' \
-  | xargs -r strip -s || true
+  | xargs -r strip -s || echo "Failed strip"
+
+
+FROM ${BASE_IMAGE}
+
+COPY --from=builder ${SPACK_HOME} ${SPACK_HOME}
+COPY --from=builder ${SPACK_ROOT} ${SPACK_ROOT}
diff --git a/4-mpi/Dockerfile b/4-mpi/Dockerfile
--- a/4-mpi/Dockerfile
+++ b/4-mpi/Dockerfile
@@ -1,18 +1,29 @@
 ARG BASE_IMAGE
 
-FROM ${BASE_IMAGE}
+FROM ${BASE_IMAGE} AS builder
 
 ARG MPI
 ARG SPACK_INSTALL_ARGS
 
-ENV SPACK_INSTALL_ARGS=${SPACK_INSTALL_ARGS:-"--verbose --test=all --fail-fast"}
+ENV SPACK_INSTALL_ARGS=${SPACK_INSTALL_ARGS:-"--show-log-on-error --test=all --fail-fast"}
 ENV MPI=${MPI}
 
 SHELL ["/usr/local/bin/spack-env", "/bin/bash", "-c"]
 
-RUN set -ex \
- && spack solve                         --reuse "${MPI}" target=x86_64 "%${COMPILER}" "^cmake~ncurses~ownlibs" \
- && spack install ${SPACK_INSTALL_ARGS} --reuse "${MPI}" target=x86_64 "%${COMPILER}" "^cmake~ncurses~ownlibs" \
- && find -L ${SPACK_ROOT}/opt/spack -type f -exec readlink -f '{}' \; \
+RUN spack solve -I                      --reuse "${MPI} target=x86_64 cmake~ncurses~ownlibs^curl tls=openssl"\
+ && spack install ${SPACK_INSTALL_ARGS} --reuse "${MPI} target=x86_64 cmake~ncurses~ownlibs^curl tls=openssl"
+
+RUN spack clean -a
+
+RUN find -L ${SPACK_ROOT}/opt/spack -type f -exec readlink -f '{}' \; \
   | xargs file -i | awk -F: '/(x-executable|x-archive|x-sharedlib); charset=binary/ {print $1}' \
-  | xargs -r strip -s || true
+  | xargs -r strip -s || echo "Failed strip"
+
+
+FROM ${BASE_IMAGE}
+
+ARG MPI
+ENV MPI=${MPI}
+
+COPY --from=builder ${SPACK_HOME} ${SPACK_HOME}
+COPY --from=builder ${SPACK_ROOT} ${SPACK_ROOT}
diff --git a/5-optlibs/Dockerfile b/5-optlibs/Dockerfile
--- a/5-optlibs/Dockerfile
+++ b/5-optlibs/Dockerfile
@@ -1,32 +1,43 @@
 ARG BASE_IMAGE
 
-FROM ${BASE_IMAGE}
+FROM ${BASE_IMAGE} AS builder
 
 ARG OPTLIBS_VERSION
 ARG SPACK_INSTALL_ARGS
 
-ENV SPACK_INSTALL_ARGS=${SPACK_INSTALL_ARGS:-"--verbose --test=all --fail-fast"}
+ENV SPACK_INSTALL_ARGS=${SPACK_INSTALL_ARGS:-"--show-log-on-error --test=all --fail-fast"}
 ENV OPTLIBS_VERSION=${OPTLIBS_VERSION}
 
-RUN git clone --depth 1 https://github.com/leobago/fti-spack ${SPACK_ROOT}/var/spack/repos/fti \
- && git clone --depth 1 https://gitlab.version.fz-juelich.de/SIONlib/spack-repository.git ${SPACK_ROOT}/var/spack/repos/SIONlib \
- && git clone --depth 1 https://github.com/pdidev/spack ${SPACK_ROOT}/var/spack/repos/pdi \
- && rm -rf ${SPACK_ROOT}/var/spack/repos/*/.git \
- && spack repo add ${SPACK_ROOT}/var/spack/repos/fti \
- && spack repo add ${SPACK_ROOT}/var/spack/repos/SIONlib \
- && spack repo add ${SPACK_ROOT}/var/spack/repos/pdi \
- && find -L ${SPACK_ROOT}/opt/spack -type f -exec readlink -f '{}' \; \
-  | xargs file -i | awk -F: '/x-executable; charset=binary/ {print $1}' \
-  | xargs strip -s
+RUN git clone --depth 1 https://github.com/leobago/fti-spack ${SPACK_ROOT}/var/spack/repos/fti
+RUN rm -rf ${SPACK_ROOT}/var/spack/repos/fti/.git
+RUN spack repo add ${SPACK_ROOT}/var/spack/repos/fti
 
-RUN mkdir /opt/optlibs-env
-COPY ${OPTLIBS_VERSION}.yaml /opt/optlibs-env/spack.yaml
-RUN sed -i -e "s/@COMPILER@/${COMPILER}/" -e "s/@MPI@/${MPI}/" /opt/optlibs-env/spack.yaml \
- && spack env activate /opt/optlibs-env \
+RUN git clone --depth 1 https://gitlab.version.fz-juelich.de/SIONlib/spack-repository.git ${SPACK_ROOT}/var/spack/repos/SIONlib
+RUN rm -rf ${SPACK_ROOT}/var/spack/repos/SIONlib/.git
+RUN spack repo add ${SPACK_ROOT}/var/spack/repos/SIONlib
+
+RUN git clone --depth 1 https://github.com/pdidev/spack ${SPACK_ROOT}/var/spack/repos/pdi
+RUN rm -rf ${SPACK_ROOT}/var/spack/repos/pdi/.git
+RUN spack repo add ${SPACK_ROOT}/var/spack/repos/pdi
+
+RUN mkdir ${SPACK_ROOT}/var/environments/optlibs
+COPY ${OPTLIBS_VERSION}.yaml ${SPACK_ROOT}/var/environments/optlibs/spack.yaml
+RUN sed -i -e "s/@COMPILER@/${COMPILER}/" -e "s/@MPI@/${MPI}/" ${SPACK_ROOT}/var/environments/optlibs/spack.yaml
+
+RUN spack env activate ${SPACK_ROOT}/var/environments/optlibs \
  && spack config add "packages:all:target:[x86_64]" \
  && spack config add "packages:all:compiler:[${COMPILER}]" \
  && spack concretize --test=all --reuse \
- && spack install ${SPACK_INSTALL_ARGS} \
- && find -L ${SPACK_ROOT}/opt/spack -type f -exec readlink -f '{}' \; \
+ && spack install ${SPACK_INSTALL_ARGS} --reuse
+
+RUN spack clean -a
+
+RUN find -L ${SPACK_ROOT}/opt/spack -type f -exec readlink -f '{}' \; \
   | xargs file -i | awk -F: '/(x-executable|x-archive|x-sharedlib); charset=binary/ {print $1}' \
-  | xargs -r strip -s || true
+  | xargs -r strip -s || echo "Failed strip"
+
+
+FROM ${BASE_IMAGE}
+
+COPY --from=builder ${SPACK_HOME} ${SPACK_HOME}
+COPY --from=builder ${SPACK_ROOT} ${SPACK_ROOT}
